# Generated by Django 2.0 on 2018-02-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdcAutomationRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=2000)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PdcAutomationUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=2000)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
